### PR TITLE
Fixes dim text on google buttons

### PR DESCRIPTION
**Pull request by treeder**
Screenshot 2021-04-01 10 41 33 AM

### CODE REVIEW

**Comment by treeder** [comment]
@ZaynJarvis can we get this merged and published?

**Comment by ZaynJarvis** [comment]
I think the black google button is not encouraged from their design guidelines. https://developers.google.com/identity/branding-guidelines
If you really want a black text Google Button, you can use button builder for that.

**Comment by treeder** [comment]
All I did was change the `textColor` on a white button so it doesn't look disabled. This is how it looks now:

image

This doesn't change anything else.

**Comment by ZaynJarvis** [comment]
yea, but look, from the guidelines, the button text is not black (#000) either.
image

If you could find the exact colour for that, I would really appreciate it. I forgot why I set the text color with 0.54 opacity already.

**Comment by sowsan** [comment]
Any idea when this PR will be merged?

**Comment by treeder** [comment]
I'm assuming never based on the comments, but you can use our fork with: 

```
  flutter_signin_button:
    git:
      url: https://github.com/treeder/Flutter-Sign-in-Button.git
      ref: patch-1
```

**Pull request closed without merging**
