### PR TITLE
Workaround: add button on top to handle ripple

### PR DESCRIPTION
**Pull request by bounty1342**
https://stackoverflow.com/questions/48066321/inkwell-ripple-over-top-of-image-in-gridtile-in-flutter

Maybe some reffactor needed, or expose the color of the ripple effect can be usefull.

Hope this help.

Ripple on Google

### CODE REVIEW

**Comment by ZaynJarvis** [comment]
LGTM； however, width and margin looks like hard code number to me. Will check before merge in next release

**Comment by kkizlaitis** [comment]
I checked out this PR and although at first glance it seemed fine, I noticed a bug with it.

In @bounty1342 's implementation, now multiple widgets get the `onPressed` variable: `InkWell` and `SignInButtonBuilder` (which is then passed to `MaterialButton`). The splash effect indeed works fine when pressing **on the middle** of the button. The problem is that `MaterialButton` is bigger than `InkWell`, so you can press a bit outside of the button and the touch will be passed to `MaterialButton` **but not to `InkWell`**. So the splash bug still remains in that scenario :/

**Comment by bounty1342** [comment]
> I checked out this PR and although at first glance it seemed fine, I noticed a bug with it.
> 
> In @bounty1342 's implementation, now multiple widgets get the `onPressed` variable: `InkWell` and `SignInButtonBuilder` (which is then passed to `MaterialButton`). The splash effect indeed works fine when pressing **on the middle** of the button. The problem is that `MaterialButton` is bigger than `InkWell`, so you can press a bit outside of the button and the touch will be passed to `MaterialButton` **but not to `InkWell`**. So the splash bug still remains in that scenario :/

Just switching the material and the inkWell should do the trick.

**Comment by ZaynJarvis** [comment]
> > I checked out this PR and although at first glance it seemed fine, I noticed a bug with it.
> > In @bounty1342 's implementation, now multiple widgets get the `onPressed` variable: `InkWell` and `SignInButtonBuilder` (which is then passed to `MaterialButton`). The splash effect indeed works fine when pressing **on the middle** of the button. The problem is that `MaterialButton` is bigger than `InkWell`, so you can press a bit outside of the button and the touch will be passed to `MaterialButton` **but not to `InkWell`**. So the splash bug still remains in that scenario :/
> 
> Just switching the material and the inkWell should do the trick.


could you explain more on this? Maybe fix it with a new commit and resolve the conflicts. Thank you!

**Comment by ZaynJarvis** [comment]
closed since haven't been updated for long

**Pull request closed without merging**
